# Generated by Django 3.1.2 on 2020-11-12 11:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201111_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 11, 55, 14, 833801, tzinfo=utc)),
        ),
    ]
